const LESSONS=[
 {title:'风水真正看什么',sub:'基础认知 · 藏风得水',type:'embrace',lead:'风水不是摆放吉祥物，而是观察环境中的风、水、山形与建筑如何影响人的居住。',observe:'先看图：中心位置为什么比两侧开口处更容易“聚气”？',keys:[['藏风','四周有高低适度的山或建筑环抱，使气流进入后能够停留。'],['得水','水流或道路宜曲折、环抱、停聚，不宜直冲直泄。'],['总纲','山环水抱是最直观的好环境模型。']],good:['山环水抱','背后有靠、左右有护、前方开阔且水势环抱。'],bad:['风吹水劫','四周空旷、气流直冲、水路直去，难以停聚。'],q:'图中中心位置的核心优势是什么？',a:['摆放了吉祥物','山水形成环抱','建筑越高越好'],correct:1,why:'风水首先看真实环境。山与水形成环抱，才有藏风聚气的条件。',source:'《风水第一课》1–2讲；《杨公风水初级》何为风水'},
 {title:'四象如何定位',sub:'基础认知 · 前后左右',type:'four',lead:'站在穴位或住宅向外看，后为玄武、前为朱雀、左为青龙、右为白虎。',observe:'记住观察视角：不是看地图的固定东南西北，而是以住宅坐向为中心。',keys:[['玄武','后方，主靠山与承托，宜稳厚有力。'],['朱雀','前方，主明堂与视野，宜开阔有情。'],['龙虎','左右护卫，宜高低协调、环抱而不相斗。']],good:['四象有情','后有靠、前有堂、左右环抱，整体协调。'],bad:['四象失位','背后空虚、前方逼压、龙虎反背或相斗。'],q:'面向住宅前方观察时，左手边称为什么？',a:['白虎','青龙','玄武'],correct:1,why:'以穴位或住宅向外看的视角，左青龙、右白虎。',source:'《杨公风水初级》察砂；《家居风水高级课程》四象'},
 {title:'明堂不是一块空地',sub:'察砂 · 内中外明堂',type:'hall',lead:'明堂是住宅或穴前承接、停聚气流的空间，可分内明堂、中明堂和外明堂。',observe:'观察三层空间：离住宅最近的是内明堂，远处开阔层次依次向外展开。',keys:[['内明堂','最贴近住宅，关系到日常活动与即时承接。'],['中明堂','连接内外，宜平整、聚合、不逼不散。'],['外明堂','远方大环境，决定整体格局与气势。']],good:['明堂舒展','层次分明、大小适中、开阔而不空散。'],bad:['逼压或倾泻','过窄受压，或一望无收、气势直走。'],q:'住宅门前最近的一层空间称为什么？',a:['内明堂','外明堂','水口'],correct:0,why:'紧邻住宅或穴位的承接空间称内明堂。',source:'《家居风水高级课程》城市风水察砂'},
 {title:'木星与火星',sub:'地理五星 · 先辨轮廓',type:'peaks',lead:'辨山先看整体轮廓。木星高直，火星尖锐；一个主生发挺拔，一个主炎上变化。',observe:'不要纠结局部石块，先眯眼看山体最大的外轮廓。',keys:[['木星','形体高直、顶部圆秀，像树木向上生长。'],['火星','尖峰耸起、变化强烈，常见多个尖角。'],['辨形法','先看大轮廓，再看是否清秀、端正、有情。']],good:['秀丽端正','轮廓清楚、形体完整、顾穴有情。'],bad:['破碎粗恶','尖碎杂乱、歪斜崩缺、形体无情。'],q:'山峰尖锐上耸、轮廓如火焰，更接近哪一星？',a:['木星','火星','土星'],correct:1,why:'火星的基本视觉特征是尖、锐、炎上。',source:'《杨公风水初级》地理五星'},
 {title:'土星、金星与水星',sub:'地理五星 · 圆方曲',type:'shapes',lead:'土星多方平，金星多圆润，水星多曲折。辨形关键是抓住“方、圆、曲”三个字。',observe:'比较三种轮廓，不要用山的颜色判断五行。',keys:[['土星','顶部平整、形体厚重，取方正承载之象。'],['金星','轮廓圆润饱满，取收敛完整之象。'],['水星','起伏波曲、连绵流动，取变化流行之象。']],good:['形真体正','主体轮廓鲜明，不混乱、不破碎。'],bad:['牵强取类','只看一个小角落，忽略整座山的主体。'],q:'轮廓圆润饱满的山体，首先考虑哪一星？',a:['金星','水星','火星'],correct:0,why:'金星以圆润、饱满、收敛为基本轮廓。',source:'《杨公风水初级》地理五星'},
 {title:'什么是真过峡',sub:'寻龙 · 龙的过峡',type:'pass',lead:'龙脉行走中由宽厚转为狭窄，再重新展开的连接处称为过峡，是观察龙气是否连续的重要位置。',observe:'找图中两段山体之间最细的连接处，并看两侧是否有护送。',keys:[['束气','过峡处通常收窄，像把行走的气势暂时束紧。'],['护送','两侧有山体夹护、迎送，比孤露受风更佳。'],['连续','过峡前后山势要有来有去，不能只见断裂。']],good:['蜂腰鹤膝','中间束细、前后有力、左右有护送。'],bad:['生硬断裂','完全断开、无护无送，不能见窄处就认作过峡。'],q:'判断过峡时，除了“窄”还要重点看什么？',a:['山上树木多少','前后连续与左右护送','离城市多远'],correct:1,why:'真正的过峡要观察龙脉前后连续，以及两侧是否有迎送护卫。',source:'《杨公风水初级》龙的过峡'},
 {title:'察砂先看秀与恶',sub:'察砂 · 第一标准',type:'goodbad',lead:'砂是穴场周围有作用的山体或建筑。第一眼先分清秀与粗恶，再谈方位和名称。',observe:'同样是高起的形体，左侧线条完整，右侧尖碎破损，感受完全不同。',keys:[['秀丽','轮廓清晰、表面完整、比例协调，使人感到安定。'],['粗恶','崩破、尖碎、歪斜、逼迫，视觉上躁乱不安。'],['先形后理','形体不过关，不急着套理气名词。']],good:['秀而有情','端正、圆润、朝拱、距离适中。'],bad:['粗恶无情','尖射、崩破、反背、逼压、相斗。'],q:'察砂的第一步更适合做什么？',a:['先算飞星','先分秀丽与粗恶','先看房主八字'],correct:1,why:'形法观察先从肉眼可见的形体品质入手。',source:'《杨公风水初级》察砂；《家居风水高级课程》察砂六标准'},
 {title:'玉带与反弓',sub:'观水 · 环抱和外弓',type:'water',lead:'水流或道路弯曲时，弯内侧如腰带环抱称玉带；弯外侧受弓背冲射称反弓。',observe:'同一条弯曲水路，两侧吉凶感受不同，关键看你位于内弯还是外弯。',keys:[['玉带','位于弯曲内侧，水路呈环抱、兜收之势。'],['反弓','位于弯曲外侧，弧线背向住宅，动势向外冲甩。'],['道路同看','城市道路也可按水的动势观察，但要结合车流和距离。']],good:['曲水环抱','弧线柔和、速度适中、在前方形成兜收。'],bad:['反弓冲射','位于外弯受冲，尤其车流快速时更需注意。'],q:'住宅位于道路弯曲的内侧，路形像腰带环抱，称为什么？',a:['反弓','玉带','直泄'],correct:1,why:'弯曲内侧形成环抱，是玉带形；外侧才是反弓。',source:'《风水第一课》；《杨公风水初级》观水'},
 {title:'水要聚，不要直泄',sub:'观水 · 动静与收放',type:'flow',lead:'好水不只在方向，更在形态与速度。曲折、停聚、有关栏，通常比直来直去更容易形成聚合。',observe:'观察两条水路：一条在前方回旋停聚，一条从门前笔直穿过。',keys:[['聚','水面或道路在明堂前停留、回旋、交汇。'],['关栏','去水处有收束，不是一眼直去无踪。'],['有情','来水舒缓、朝向明确，不冲不割。']],good:['水聚明堂','水势缓、曲、停，明堂有承接。'],bad:['直冲直泄','速度快、方向硬、来去无收。'],q:'以下哪种水形更符合“得水”？',a:['笔直快速穿过','在明堂前曲折停聚','从屋后陡泄'],correct:1,why:'“得水”重在水势有情、能够停聚，而不是只要看见水。',source:'《家居风水高级课程》现代城市风水如何观水'},
 {title:'龙虎环抱还是相斗',sub:'察砂 · 左右护卫',type:'dragonTiger',lead:'青龙白虎的重点不是机械比较谁高，而是看左右是否协调、环抱、护卫中心。',observe:'看两侧山体的走势：是向中心回顾，还是尖头相冲、向外反背？',keys:[['环抱','左右形体向内弯顾，形成稳定的围合感。'],['协调','高低、远近要结合整体，不以“左必高、右必低”一刀切。'],['相斗','两侧尖锐对冲、交叉逼压，形势紧张。']],good:['龙虎有情','左右护卫、内顾、不过分逼压。'],bad:['反背相斗','向外飞走，或尖锐交战、欺压失衡。'],q:'判断龙虎最重要的核心是什么？',a:['青龙永远要更高','左右是否协调有情','必须完全对称'],correct:1,why:'龙虎看的是护卫与有情，不能只用高低或绝对对称判断。',source:'《杨公风水初级》察砂'},
 {title:'靠山有力，不等于越近越高',sub:'城市选宅 · 玄武',type:'backing',lead:'住宅后方有稳定承托是“有靠”，但靠山或建筑过近过高，也可能形成逼压。',observe:'比较适度承托与贴身高墙，两者都有“东西在后面”，感受却不同。',keys:[['有靠','后方稳定、完整，距离与高度适中。'],['逼压','过近、过高、压迫采光通风，心理和环境都受影响。'],['城市借形','后楼、台地、成片建筑都可作为现代环境中的“靠”。']],good:['稳而不压','后方有承托，仍保留适当距离、光线和空气。'],bad:['高近逼压','贴身高耸、阴暗闭塞，不能因“有靠”就判吉。'],q:'后方建筑越高越近，就一定越好吗？',a:['一定更好','不一定，要看距离与逼压','只看建筑价格'],correct:1,why:'风水强调适度与协调，有靠和逼压必须区分。',source:'《家居风水高级课程》城市风水点穴'},
 {title:'城市选宅六步观察',sub:'综合应用 · 从外到内',type:'city',lead:'城市环境也能按龙、砂、水、穴的思路观察。先看大环境，再逐步缩小到楼栋和住宅。',observe:'面对一处住宅，不急着下结论，按顺序把环境层级看全。',keys:[['先外后内','先片区与道路，再小区、楼栋、户型。'],['先形后方','先看形体是否舒服，再讨论方位与理气。'],['六步','后靠、前堂、左右、道路水势、风口逼压、整体整洁。']],good:['层层筛选','大环境合格，再看局部；明显形煞先排除。'],bad:['只看一处','只凭门向、楼层或一个摆件就判断整体。'],q:'城市选宅更合理的观察顺序是什么？',a:['先户型摆件，再看城市','先大环境，再到楼栋户型','只看大门方向'],correct:1,why:'环境影响有层级，应先外后内、先大后小。',source:'《家居风水高级课程》现代城市寻龙与选宅'}
];

const $=s=>document.querySelector(s);const todayKey=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
const state=()=>{try{return JSON.parse(localStorage.getItem('guanshan_progress')||'{}')}catch(e){return{}}};
const save=s=>localStorage.setItem('guanshan_progress',JSON.stringify(s));
function currentIndex(){const s=state();for(let i=0;i<LESSONS.length;i++)if(!s[i])return i;return Math.floor(Date.now()/864e5)%LESSONS.length}

function visual(type,dark=false){const bg=dark?'#131719':'#e6e2d9',line=dark?'#b89a67':'#756b59',soft=dark?'#61706c':'#a69d8c',water=dark?'#647e84':'#7898a0';
 const wrap=x=>`<svg viewBox="0 0 420 220" role="img" aria-label="风水识形示意图"><rect width="420" height="220" fill="${bg}"/>${x}</svg>`;
 const ground=`<path d="M0 178 Q90 168 160 180 T420 176 V220 H0Z" fill="${soft}" opacity=".17"/>`;
 const home=`<path d="M188 153h44v31h-44zM183 153l27-20 27 20" fill="none" stroke="${line}" stroke-width="3"/>`;
 const mountain=(x,y,s=1)=>`<path d="M${x} ${y} Q${x+22*s} ${y-55*s} ${x+48*s} ${y} Q${x+70*s} ${y-34*s} ${x+92*s} ${y}" fill="none" stroke="${line}" stroke-width="3"/>`;
 if(type==='embrace')return wrap(ground+mountain(20,155,1.15)+mountain(292,155,1.1)+home+`<path d="M65 187 Q210 120 355 187" fill="none" stroke="${water}" stroke-width="8" opacity=".9"/><path d="M92 169 Q145 122 177 145M328 169 Q275 122 243 145" fill="none" stroke="${line}" stroke-width="2" opacity=".75"/>`);
 if(type==='four')return wrap(ground+home+`<path d="M150 165Q112 116 62 132M270 165Q308 116 358 132M160 120Q210 60 260 120" fill="none" stroke="${line}" stroke-width="4"/><text x="210" y="42" text-anchor="middle" fill="${line}">玄武</text><text x="52" y="112" fill="${line}">青龙</text><text x="326" y="112" fill="${line}">白虎</text><text x="210" y="207" text-anchor="middle" fill="${water}">朱雀 · 明堂</text>`);
 if(type==='hall')return wrap(home+`<path d="M150 184h120M110 201h200M55 216h310" stroke="${line}" stroke-width="2"/><text x="285" y="181" fill="${line}">内</text><text x="325" y="199" fill="${line}">中</text><text x="370" y="216" fill="${line}">外</text><path d="M110 120Q70 80 30 130M310 120Q350 80 390 130" fill="none" stroke="${soft}" stroke-width="5"/>`);
 if(type==='peaks')return wrap(ground+`<path d="M38 180Q85 48 130 180" fill="none" stroke="${line}" stroke-width="5"/><text x="85" y="205" text-anchor="middle" fill="${line}">木 · 高直</text><path d="M215 180L252 75L273 128L300 42L344 180" fill="none" stroke="${line}" stroke-width="5"/><text x="280" y="205" text-anchor="middle" fill="${line}">火 · 尖耸</text>`);
 if(type==='shapes')return wrap(ground+`<path d="M20 180L45 105H125L150 180" fill="none" stroke="${line}" stroke-width="5"/><path d="M155 180Q210 74 265 180" fill="none" stroke="${line}" stroke-width="5"/><path d="M275 180Q300 120 325 170Q350 98 400 180" fill="none" stroke="${line}" stroke-width="5"/><text x="85" y="205" text-anchor="middle" fill="${line}">土 · 方</text><text x="210" y="205" text-anchor="middle" fill="${line}">金 · 圆</text><text x="340" y="205" text-anchor="middle" fill="${line}">水 · 曲</text>`);
 if(type==='pass')return wrap(ground+`<path d="M0 165Q55 56 128 145Q170 182 210 151Q250 182 292 145Q365 56 420 165" fill="none" stroke="${line}" stroke-width="5"/><circle cx="210" cy="151" r="11" fill="none" stroke="${water}" stroke-width="3"/><text x="210" y="128" text-anchor="middle" fill="${water}">过峡</text><path d="M163 171Q185 150 202 163M257 171Q235 150 218 163" fill="none" stroke="${soft}" stroke-width="3"/>`);
 if(type==='goodbad')return wrap(` <path d="M20 180Q80 60 150 180" fill="none" stroke="${line}" stroke-width="5"/><circle cx="85" cy="105" r="28" fill="none" stroke="${soft}"/><text x="85" y="205" text-anchor="middle" fill="${line}">秀丽端正</text><path d="M230 180L252 126L267 145L283 75L300 132L321 92L348 180" fill="none" stroke="${line}" stroke-width="5"/><path d="M270 72l20 20M290 72l-20 20" stroke="${water}" stroke-width="3"/><text x="290" y="205" text-anchor="middle" fill="${line}">尖碎粗恶</text>`);
 if(type==='water')return wrap(home+`<path d="M20 190Q210 75 400 190" fill="none" stroke="${water}" stroke-width="14"/><text x="210" y="108" text-anchor="middle" fill="${line}">内弯 · 玉带</text><text x="210" y="213" text-anchor="middle" fill="${line}">外弯 · 反弓</text>`);
 if(type==='flow')return wrap(` <path d="M40 10Q160 70 80 125Q20 180 180 200" fill="none" stroke="${water}" stroke-width="12"/><circle cx="110" cy="123" r="34" fill="none" stroke="${line}" stroke-width="2"/><text x="110" y="128" text-anchor="middle" fill="${line}">聚</text><path d="M300 0L300 220" stroke="${water}" stroke-width="12"/><path d="M275 78l25 28 25-28M275 135l25 28 25-28" fill="none" stroke="${line}" stroke-width="3"/><text x="340" y="112" fill="${line}">直泄</text>`);
 if(type==='dragonTiger')return wrap(home+`<path d="M0 172Q62 65 172 155M420 172Q358 65 248 155" fill="none" stroke="${line}" stroke-width="6"/><path d="M112 111Q152 127 175 154M308 111Q268 127 245 154" fill="none" stroke="${water}" stroke-width="2"/><text x="65" y="195" fill="${line}">青龙</text><text x="325" y="195" fill="${line}">白虎</text>`);
 if(type==='backing')return wrap(ground+home+`<path d="M115 135Q210 45 305 135" fill="none" stroke="${line}" stroke-width="7"/><path d="M145 150h130" stroke="${soft}" stroke-dasharray="5 5"/><text x="210" y="31" text-anchor="middle" fill="${line}">稳而不压</text>`);
 return wrap(ground+`<rect x="150" y="120" width="120" height="65" fill="none" stroke="${line}" stroke-width="3"/><path d="M130 120Q210 40 290 120M45 185Q210 130 375 185" fill="none" stroke="${soft}" stroke-width="4"/><circle cx="210" cy="150" r="13" fill="${water}"/><text x="210" y="25" text-anchor="middle" fill="${line}">先外后内 · 逐层观察</text>`);
}

function render(){const i=currentIndex(),l=LESSONS[i],s=state(),done=Object.keys(s).filter(k=>s[k]).length;
 $('#today').innerHTML=`<div class="today-top"><span class="today-label">今日识形 · 第 ${String(i+1).padStart(2,'0')} 课</span><span class="today-time">约 8 分钟</span></div><h2>${l.title}</h2><p class="today-desc">${l.sub}</p><div class="today-visual">${visual(l.type,true)}</div><button class="start" data-open="${i}">${s[i]?'复习今日内容':'开始今日一课'}</button>${s[i]?'<div class="done-banner">✓ 今日课程已完成</div>':''}`;
 $('#path').innerHTML=LESSONS.map((x,n)=>`<button class="path-item ${n===i?'active':''} ${s[n]?'done':''}" data-open="${n}"><span class="path-no">${String(n+1).padStart(2,'0')}</span><span class="path-copy"><b>${x.title}</b><span>${x.sub}</span></span><span class="path-state">${s[n]?'✓':'›'}</span></button>`).join('');
 $('#path-progress').textContent=`${done} / ${LESSONS.length}`;renderStreak();
}
function renderStreak(){let hist={};try{hist=JSON.parse(localStorage.getItem('guanshan_history')||'{}')}catch(e){}let n=0,d=new Date();for(let k=0;k<90;k++){const key=`${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`;if(hist[key]){n++;d.setDate(d.getDate()-1)}else if(k===0)d.setDate(d.getDate()-1);else break}$('#streak').innerHTML=`<b>${n}</b><span>连续学习</span>`}
const EXPAND={
 embrace:['风水判断从真实环境出发。环抱会改变风速、视线与空间边界，水路的曲直又影响人流、车流和湿度，所以“藏风得水”既是传统术语，也是观察环境关系的总纲。','站在住宅外先转一圈：看风从哪里来、在哪里变快；再看水路或道路从哪里来、在哪里转弯与停留。把观察到的证据写下来，再谈吉凶。','把“没有风”误当藏风，或把“看见水”直接当得水。真正要看的是适度流通、曲缓停聚与整体协调。'],
 four:['四象是把复杂环境转成前后左右四组关系。它的价值在于建立稳定观察次序，而不是把每个方向机械对应成某种结果。','先确定住宅朝向，再站在中心向外看。分别拍下后、前、左、右四张照片，比较它们的高度、距离、走势和是否顾宅。','拿地图的东南西北代替住宅视角；或只记“左高右低”，忽略逼压、反背、距离与整体比例。'],
 hall:['明堂承担承接与缓冲。过窄会产生压迫，过度空散又缺少边界；理想状态是从近到远逐步展开，同时仍能感到围合。','从门前最近的可用空间开始，依次观察小区内部、道路广场和远方开阔面，记录每层是否平整、受冲、受压或外泄。','把所有空地都叫明堂；只追求越大越好；忽略停车场、高架、强风和快速车流对空间的真实影响。'],
 peaks:['五星不是给山贴标签，而是训练你识别轮廓。先能稳定辨认“直、尖、方、圆、曲”，之后才有条件讨论不同星体的组合与结穴。','把图片缩小或眯眼看，忽略植被与石纹，只描最大轮廓；再检查主体是否完整、端正、秀丽。','凭颜色、树种或一个局部尖角定星；山体混合时强迫归成单一星体。'],
 shapes:['方、圆、曲是三种基本视觉语言。山体常为复合形，应先辨主星，再描述辅星与过渡，避免非黑即白。','用手指沿山脊线移动：平台感强看土，圆弧收敛看金，连续波动看水；最后再判断主次。','把“土”理解成泥土、“金”理解成石头；五行山形判断看的是轮廓，不是材质。'],
 pass:['过峡像文章中的收束和转折：前段山势的力量在狭处集中，再向后展开。是否连续、有护送，比单纯狭窄更重要。','从卫星图与现场两个尺度寻找山脊收窄处，沿线确认前后来脉，并观察左右是否有夹护、风口是否过强。','看到两个山头之间的低处就叫过峡；忽略人工开挖、道路切断和完全脱脉。'],
 goodbad:['秀恶判断是形法的第一层筛选。它不是审美偏好，而是观察完整性、稳定感、边缘形态以及对中心空间造成的压力。','先不用任何术语，只写五个形容词描述眼前形体；再将它们归入完整/破碎、端正/歪斜、柔和/尖锐。','只因为山高、建筑贵或造型奇特就判吉；忽略距离后把远处小尖角夸大成严重形煞。'],
 water:['弯曲水路的内外侧承受的动势不同。内弯形成包裹，外弯呈向外甩出的趋势；城市道路还要加入车速、坡度和防护条件。','在地图上画出道路或河流中心线，标出住宅位于曲线内侧还是外侧，再到现场确认距离、高差和流速。','只看平面弧线，不看距离与高差；把轻微弯路也夸大成反弓。'],
 flow:['“聚”是水势在空间中减速、回旋或交汇，“泄”是快速穿越、毫无收束。判断时要同时看形状、速度、去向和明堂承接。','观察雨后水流、日常车流和人流：哪里会慢下来，哪里快速离开；这些真实动线比静态照片更有价值。','认为水越多越好；忽略噪声、污染、洪涝和安全等现实问题。'],
 dragonTiger:['龙虎代表中心左右两侧的护卫关系。理想不是绝对对称，而是彼此协调、向内顾护且不让中心感到压迫。','站在门前或阳台中心，比较左右建筑的高度、距离、朝向与边缘；特别留意尖角是否相冲、空缺是否受强风。','死背青龙必须高于白虎；脱离坐向看左右；把正常城市高差一概判凶。'],
 backing:['靠山的作用是稳定与承托，但尺度失衡会由“靠”变“压”。现代住宅还必须把采光、通风、消防间距纳入判断。','观察后方建筑或山体的完整度、距离和高度；进入室内感受是否阴暗、潮湿、压迫，再作综合判断。','只要后面有高楼就判有靠；忽略贴墙、挡光、落石和结构安全。'],
 city:['城市风水是分层筛选：大环境决定上限，楼栋与户型决定日常体验，室内调整只能处理最后一层问题。','按片区—小区—楼栋—楼层—户型—室内六层拍照记录，每层先排除一项最明显的问题。','一进门就讨论床、灶和摆件，却没有看道路、噪声、风口、采光与楼栋关系。']
};
const REL_CAT={embrace:'基础入门',four:'基础入门',hall:'龙砂水穴',peaks:'龙砂水穴',shapes:'龙砂水穴',pass:'龙砂水穴',goodbad:'龙砂水穴',water:'龙砂水穴',flow:'龙砂水穴',dragonTiger:'龙砂水穴',backing:'城市家居',city:'城市家居'};
function openLesson(i){
 const l=LESSONS[i],s=state(),ex=EXPAND[l.type],related=LIBRARY.filter(x=>x.cat===REL_CAT[l.type]&&!l.title.includes(x.title)).slice((i*3)%8,(i*3)%8+4);
 $('#lesson-content').innerHTML=`<p class="lesson-kicker">LESSON ${String(i+1).padStart(2,'0')} · ${l.sub}</p><h2>${l.title}</h2><p class="lesson-lead">${l.lead}</p><div class="lesson-visual">${visual(l.type)}</div><div class="observe"><b>先观察</b><br>${l.observe}</div>
 <div class="lesson-section"><span>01</span><div><h3>核心知识</h3><div class="keypoints">${l.keys.map((k,n)=>`<div class="keypoint"><i>${n+1}</i><div><b>${k[0]}</b><p>${k[1]}</p></div></div>`).join('')}</div></div></div>
 <div class="lesson-section"><span>02</span><div><h3>为什么这样判断</h3><p>${ex[0]}</p></div></div>
 <div class="lesson-section"><span>03</span><div><h3>现场怎么用</h3><p>${ex[1]}</p></div></div>
 <div class="compare"><div class="good"><b>✓ ${l.good[0]}</b><p>${l.good[1]}</p></div><div class="bad"><b>× ${l.bad[0]}</b><p>${l.bad[1]}</p></div></div>
 <div class="mistake"><b>常见误判</b><p>${ex[2]}</p></div>
 <div class="quiz"><h3>判断一下</h3><p>${l.q}</p><div class="answers">${l.a.map((a,n)=>`<button type="button" data-answer="${n}" data-lesson="${i}">${a}</button>`).join('')}</div><p class="feedback" id="feedback"></p></div>
 <div class="related"><h3>相关知识</h3>${related.map(x=>`<button type="button" data-knowledge="${x.id}"><b>${x.title}</b><span>${x.summary}</span></button>`).join('')}</div>
 <button type="button" class="complete ${s[i]?'done':''}" data-complete="${i}">${s[i]?'✓ 已完成本课':'完成本课并打勾'}</button><p class="source">内容依据：${l.source} · 已重新整理为学习摘要，非原文照录</p>`;toggleSheet('#lesson-sheet',true)
}
function toggleSheet(id,on){const el=$(id);el.classList.toggle('on',on);el.setAttribute('aria-hidden',on?'false':'true');document.body.style.overflow=on?'hidden':''}
const REFS={five:['五星辨形',[['木星','高直而上，顶部圆秀'],['火星','尖锐耸起，变化强烈'],['土星','方平厚重，形体稳定'],['金星','圆润饱满，收敛完整'],['水星','波曲连绵，流动多变']]],four:['四象定位',[['玄武','住宅后方，宜稳厚有靠'],['朱雀','住宅前方，宜明堂舒展'],['青龙','向外看左侧，宜环抱有情'],['白虎','向外看右侧，宜协调护卫']]],water:['水形吉凶',[['玉带','位于弯曲内侧，环抱兜收'],['反弓','位于弯曲外侧，动势外甩'],['聚水','曲折停聚、交汇有关栏'],['直泄','笔直快速、来去无收']]],check:['城市选宅六看',[['一看后靠','稳定完整，不可过近逼压'],['二看明堂','开阔有层次，不空散'],['三看龙虎','左右协调、环抱有情'],['四看道路','曲缓有收，避直冲反弓'],['五看风口','避天斩、穿堂、强风直灌'],['六看整体','整洁明亮，先外后内']]]};
function openRef(id){const r=REFS[id];$('#ref-content').innerHTML=`<p class="lesson-kicker">QUICK REFERENCE</p><h2>${r[0]}</h2><div class="ref-list">${r[1].map(x=>`<div class="ref-row"><b>${x[0]}</b><p>${x[1]}</p></div>`).join('')}</div>`;toggleSheet('#ref-sheet',true)}
let libraryCat='全部',libraryQuery='';
function renderLibrary(){const cats=['全部',...new Set(LIBRARY.map(x=>x.cat))],items=LIBRARY.filter(x=>(libraryCat==='全部'||x.cat===libraryCat)&&(!libraryQuery||`${x.title}${x.summary}${x.source}`.includes(libraryQuery)));$('#library-tabs').innerHTML=cats.map(c=>`<button class="${c===libraryCat?'on':''}" data-lib-cat="${c}">${c}</button>`).join('');$('#library-list').innerHTML=items.map(x=>`<button class="library-item" data-knowledge="${x.id}"><span class="li-no">${String(x.id).padStart(2,'0')}</span><span><b>${x.title}</b><small>${x.cat} · ${x.source}</small></span><i>›</i></button>`).join('')||'<div class="today-desc">没有找到相关知识点</div>';$('#library-count').textContent=`${items.length} / ${LIBRARY.length}`}
function openKnowledge(id){const x=LIBRARY.find(v=>v.id===id);if(!x)return;const related=LIBRARY.filter(v=>v.cat===x.cat&&v.id!==x.id).slice(0,4);$('#ref-content').innerHTML=`<p class="lesson-kicker">KNOWLEDGE ${String(x.id).padStart(2,'0')} · ${x.cat}</p><h2>${x.title}</h2><div class="knowledge-tags"><span>${x.cat}</span><span>来源：${x.source}</span></div><div class="knowledge-card"><h3>核心要点</h3><p>${x.summary}</p></div><div class="knowledge-card"><h3>学习方法</h3><p>先回到真实图片或现场寻找可见证据，再与相近概念比较；不以单一征象直接判断整体吉凶。</p></div><div class="knowledge-card"><h3>同类知识</h3><p>${related.map(v=>v.title).join(' · ')}</p></div>`;toggleSheet('#ref-sheet',true)}
document.body.addEventListener('click',e=>{const o=e.target.closest('[data-open]');if(o){openLesson(+o.dataset.open);return}if(e.target.closest('[data-close]')){toggleSheet('#lesson-sheet',false);return}if(e.target.closest('[data-ref-close]')){toggleSheet('#ref-sheet',false);return}const lc=e.target.closest('[data-lib-cat]');if(lc){libraryCat=lc.dataset.libCat;renderLibrary();return}const kn=e.target.closest('[data-knowledge]');if(kn){openKnowledge(+kn.dataset.knowledge);return}const r=e.target.closest('[data-ref]');if(r){openRef(r.dataset.ref);return}const a=e.target.closest('[data-answer]');if(a){const l=LESSONS[+a.dataset.lesson],buttons=[...a.parentNode.children],n=+a.dataset.answer;buttons.forEach((b,j)=>b.classList.add(j===l.correct?'ok':j===n?'no':''));buttons.forEach(b=>b.disabled=true);$('#feedback').textContent=(n===l.correct?'答对了。':'再看一眼：')+l.why;return}const c=e.target.closest('[data-complete]');if(c){const i=+c.dataset.complete,s=state();s[i]=!s[i];save(s);let h={};try{h=JSON.parse(localStorage.getItem('guanshan_history')||'{}')}catch(x){}if(s[i])h[todayKey()]=true;localStorage.setItem('guanshan_history',JSON.stringify(h));c.classList.toggle('done',s[i]);c.textContent=s[i]?'✓ 已完成本课':'完成本课并打勾';render()}});
$('#library-search').addEventListener('input',e=>{libraryQuery=e.target.value.trim();renderLibrary()});
render();renderLibrary();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});
